name: Enhancement
description: "Create a feature request"
title: "[Enhancement] "
labels: ["enhancement", "triage"]
assignees:
  - Chris-RH
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: request
    attributes:
      label: Description
      description: Please describe your feature request here.
    validations:
      required: true
